thisissoon/FM-Frontend

app/index.html, app/js/fm-socket/example/PlayerCtrl.js, app/js/fm-socket/example/index.html, app/js/fm-socket/socket.js, bower.json, scripts.json
Configures socket.io to listen to thisissoon.fm socket server. Event handler's can be added by injecting `fmSocket` into a controller and calling `fmSocket.addListener(event, eventHandler)`. The eventHandler will be called with the data object passed with the event. This may include track data etc.
=> Feature: websocket interface

app/index.html, app/js/fm-api/factories/PlayerQueueResource.js, app/js/fm-api/factories/PlayerTransportResource.js, app/js/fm-player/config.js, app/js/fm-player/controllers/PlayerCtrl.js, scripts.json, tests/unit/fm-player/controllers/PlayerCtrl.js
Updates to FM-API:
- `player/playing` becomes `player/current`
- `player/playlist` becomes `player/queue`
- PlayerPlaylistResource has been renamed to PlayerQueueResource
=> Feature: update api

.dockerignore, Dockerfile.prod, nginx.conf, nginx.sources.list
This PR adds a dockerfile for production build and nginx config.
=> Feature: dockerfile

app/less/default/modules/songs.less, app/less/mobile/modules/songs.less, app/partials/player.html, bower.json
Fixes multiple artists wrapping onto new lines and displays album name instead
=> Fix: Song styling with multiple artist

app/js/fm-player/controllers/PlayerCtrl.js, tests/unit/fm-player/controllers/PlayerCtrl.js
Decrease volume step from 10 to 5.
=> Feature: step volume by 5

app/img/icons/ic_skip_next_24px.svg, app/js/fm-api/factories/PlayerTransportResource.js, app/js/fm-player/controllers/PlayerCtrl.js, app/partials/player.html, tests/unit/fm-player/controllers/PlayerCtrl.js
Implements `DELETE /player/current` endpoint for skip functionality.
=> Feature: skip

app/index.html, app/js/app.js, app/js/fm-loading-screen/loadingScreen.js, app/js/fm-player/config.js, app/less/default/modules/header.less, app/less/default/modules/loading-screen.less, app/less/main.less, app/partials/loading.html, scripts.json, tests/unit/fm-loading-screen/loadingScreen.js, tests/unit/fm-player/directives/track.js
This PR adds a loading screen when the app loads and when changing between views
=> Feature: Loading screen

app/less/default/modules/header.less, app/less/default/modules/player.less, app/less/main.less, app/less/mobile/modules/player.less, app/partials/player.html
- Fix: sidebar being on top of header in mobile
- Fix: controls layout in mobile
=> Feature: More styling fixes

bower.json, modules/oauth/index.html
This is the prototype for using oauth2 in our angular app configure for the FM-API.
=> Feature: oauth prototype

app/index.html, app/js/fm-player/controllers/PlayerCtrl.js, app/js/fm-player/controllers/SearchCtrl.js, app/js/fm-player/directives/track.js, app/less/default/core/reset.less, app/less/default/modules/header.less, app/less/default/modules/loading-screen.less, app/less/default/modules/player.less, app/less/default/modules/spotify-search.less, app/less/default/modules/tracks.less, app/less/main.less, app/less/mobile/modules/header.less, app/less/mobile/modules/player.less, app/less/mobile/modules/spotify-search.less, app/less/tablet/modules/header.less, app/less/tablet/modules/spotify-search.less, app/partials/controls.html, app/partials/header.html, app/partials/player.html, app/partials/sidebar.html, app/partials/track.html, scripts.json, tests/unit/fm-player/controllers/PlayerCtrl.js, tests/unit/fm-player/controllers/SearchCtrl.js
This PR refactors the mark up further to separate the Spotify search sidebar and the player
=> Feature: Global sidebar

app/js/fm-player/controllers/PlayerCtrl.js, tests/unit/fm-player/controllers/PlayerCtrl.js
Update spotify_uri => uri as per API update and call `init()` on `refreshPlaylist()` to fix #39
=> Fix: update spotify_uri => uri 

env.json
=> Feature: Update socket address to use https

app/index.html, app/js/fm-api/factories/RequestInterceptor.js, app/js/fm-player/app.js, app/js/fm-player/config.js, app/js/fm-player/controllers/LoginCtrl.js, app/partials/401.html, app/partials/player.html, app/partials/sidebar.html, env.json, scripts.json, tests/unit/fm-api/factories/RequestInterceptor.js, tests/unit/fm-player/controllers/LoginCtrl.js
This adds a login button, authenticated state and 401 error page. This is the final step to implement the google authentication.
=> Feature: final auth integration

app/js/fm-api/config.js, env.json
Fixes oauth redirect URI config in development.
=> Fix: dev oauth

app/js/fm-player/controllers/PlayerCtrl.js, tests/unit/fm-player/controllers/PlayerCtrl.js
New DAC has a more sensitive volume control.
=> Fix: step volume by 1 instead of 5

app/index.html, bower.json
Install from github using bower instead of using their CDN.
=> Fix: socket.io-client dependency

app/less/default/core/glyphicons.less
=> Fix: Broken font icons

app/js/player/controllers/PlayerCtrl.js
Send empty json for POST to declare content type
Fixes: #58
=> Fix: Play/pause buttons

app/index.html, app/js/alert/alert.js, app/js/alert/controllers/AlertCtrl.js, app/js/alert/services/AlertService.js, app/js/api/constants/errors.js, app/js/api/factories/RequestInterceptor.js, app/js/app.js, app/less/default/core/variables.less, app/less/default/modules/alert.less, app/less/default/modules/animations.less, app/less/main.less, app/partials/alert.html, scripts.json, tests/unit/alert/controllers/AlertCtrl.js, tests/unit/alert/services/AlertService.js
- `FM.alert` module
- Generic alert for in-view 401 errors
- Fixes #63 
`FM.alert` provides `AlertService` which can be used to set alerts like:
```
AlertService.set("Woah there! You Need to login to do that.", "warning");
```
=> Feature: alerts

bower.json, modules/visualisation/chartjs.html, modules/visualisation/d3.html, modules/visualisation/index.html
To view go to `/modules/visualisation/`. 
The Chart.js example is more comprehensive as I preferred library. The angular implementation supports nice update animations, which can be seen on the bar chart 2 seconds after the page loads.
=> Feature: initial charting prototypes

app/index.html, app/js/app.js, app/js/player/controllers/PlayerCtrl.js, app/js/playlist/controllers/PlaylistCtrl.js, bower.json, scripts.json, tests/unit/player/controllers/PlayerCtrl.js, tests/unit/playlist/controllers/PlaylistCtrl.js
This PR adds back notifications, using HTML5 notifications #77
=> Feature: notifications

app/js/player/controllers/PlayerCtrl.js, app/js/playlist/controllers/PlaylistCtrl.js, tests/unit/player/controllers/PlayerCtrl.js, tests/unit/playlist/controllers/PlaylistCtrl.js
Notifications were not using correct data for user's name, this PR fixes that and fixes the tests to ensure they catch this.
=> Fix: notification and test data

CHANGELOG.md, app/js/player/controllers/PlayerCtrl.js, app/js/playlist/controllers/PlaylistCtrl.js, tests/unit/player/controllers/PlayerCtrl.js, tests/unit/playlist/controllers/PlaylistCtrl.js
Changes in 0.0.1
* @eopa: First release
We should start doing proper releases from now on
=> Release: 0.0.1

app/index.html, app/js/api/factories/PlayerHistoryResource.js, app/js/app.js, app/js/history/controllers/HistoryCtrl.js, app/js/history/history.js, app/js/infinite-scroll/infiniteScroll.js, app/less/default/modules/animations.less, app/partials/header.html, app/partials/history.html, bower.json, scripts.json, tests/unit/history/controllers/HistoryCtrl.js, tests/unit/infinite-scroll/infiniteScroll.js
- `FM.history` module
- `/history` view - closes #64 
- infinite scrolling of history list
=> Feature: history

app/js/api/factories/PlayerHistoryResource.js
Removes extraneous boolean conversion of total pages.
=> Fix: HistoryResource response transform, for retrieving total pages value

app/less/default/modules/controls.less
=> Fix: volume slider styling on FF

CHANGELOG.md, app/index.html, app/js/api/factories/PaginationInterceptor.js, app/js/api/factories/PlayerHistoryResource.js, app/js/history/controllers/HistoryCtrl.js, app/less/default/core/normalize.less, app/less/default/modules/controls.less, scripts.json, tests/unit/api/factories/PaginationInterceptor.js, tests/unit/history/controllers/HistoryCtrl.js
* @jamesjwarren: Fix: volume slider styling on FF (#90)
* @bcmrbvm: Feature: Font smoothing (#88)
* @jamesjwarren: Feature: fix pagination meta (#87)
=> Release: 0.1.2

app/js/history/controllers/HistoryCtrl.js
Should return promise in route resolve.
=> Fix: PlayerHistoryResource promise resolve

app/index.html, app/js/player/controllers/PlayerCtrl.js, app/js/player/directives/track.js, app/js/player/player.js, app/js/player/services/TrackTimer.js, app/less/default/core/variables.less, app/less/default/modules/media.less, app/less/default/modules/progress.less, app/less/main.less, app/partials/footer.html, app/partials/track.html, scripts.json, tests/unit/player/controllers/PlayerCtrl.js, tests/unit/player/services/TrackTimer.js
This PR adds tracking the elapsed time for currently playing track with progress bar. Closes #84
=> Feature: Playback position

app/js/player/controllers/PlayerCtrl.js, app/js/player/directives/track.js, app/less/default/core/variables.less, app/less/main.less, app/partials/footer.html, app/partials/track.html, tests/unit/player/directives/track.js
Re-added popovers for buttons and user avatars
Fixes #103
=> Feature: Popovers

app/less/default/modules/media.less, app/less/default/modules/progress.less, app/less/mobile/modules/controls.less, app/less/mobile/modules/footer.less, app/partials/track.html
- Fix alignment of controls in mobile
- Fix size of progress bar to stop it growing or being hidden based song data length
- Remove unneeded animation in progress bar (this data should be a 1 to 1 representation anyway)
=> Fix: Current track styling

app/js/player/directives/track.js, app/partials/track.html, tests/unit/player/directives/track.js
=> Feature: add to playlist action in track context menu

bower.json
Update angular from 1.3.15 --> 1.3.17 and specify absolute versions for other libraries
=> Feature: Update angular

app/partials/playlist.html
=> Fix: Playlist duration total

app/index.html, app/js/app.js, app/js/notifications/notifications.js, app/js/player/controllers/PlayerCtrl.js, app/js/playlist/controllers/PlaylistCtrl.js, scripts.json, tests/unit/notifications/notifications.js, tests/unit/player/controllers/PlayerCtrl.js, tests/unit/playlist/controllers/PlaylistCtrl.js
Fixes an issue where notifications are only displayed when on the playlist page
Fixes #124
=> Fix: notifications

app/partials/track.html
Added links in tracks to go to artist and album detail views when clicking on name of artist or album
Fixes #123
=> Feature: open artist and album detail view from track

app/js/notifications/notifications.js
Found a bug where the notification service was not being run automatically.
=> Fix: Notifications not running automatically

app/js/playlist/controllers/PlaylistCtrl.js, app/partials/playlist.html, tests/unit/playlist/controllers/PlaylistCtrl.js
This PR allows the user to load more tracks if the playlist is longer than 20 tracks
=> Feature: Playlist pagination

CHANGELOG.md, app/index.html, app/js/app.js, app/js/notifications/notifications.js, app/js/player/controllers/PlayerCtrl.js, app/js/playlist/controllers/PlaylistCtrl.js, app/less/default/modules/track.less, app/partials/footer.html, app/partials/playlist.html, app/partials/track.html, scripts.json, tests/unit/notifications/notifications.js, tests/unit/player/controllers/PlayerCtrl.js, tests/unit/playlist/controllers/PlaylistCtrl.js
* @bcmrbvm: Fix: Hide controls if no tracks (#134)
* @bcmrbvm: Fix: Progress bar size (#133)
* @bcmrbvm: Feature: Playlist pagination (#132)
* @bcmrbvm: Fix: Notifications not running automatically (#127)
* @bcmrbvm: Feature: open artist and album detail view from track (#126)
* @bcmrbvm: Fix: notifications (#125)
=> Release: 0.5.0

app/index.html, app/js/player/directives/track.js, app/js/player/filter/removeLeadingZeros.js, app/js/player/player.js, app/js/playlist/controllers/PlaylistCtrl.js, app/partials/playlist.html, app/partials/track.html, scripts.json, tests/unit/player/filters/removeLeadingZeros.js
This PR updates the date filter to show hours in track time. It also adds a filter to remove hours if the duration is less than an hour.
=> Feature: Show hours in track time

app/less/default/modules/track.less, app/less/mobile/modules/track.less, app/partials/track.html
Display track duration from Spotify so track duration is visible in artist and album pages
Fixes #130
=> Feature: Display track time from spotify

app/js/search/controllers/AlbumDetailCtrl.js, app/js/search/controllers/AlbumSearchCtrl.js, app/js/search/controllers/ArtistDetailCtrl.js, app/js/search/controllers/ArtistSearchCtrl.js, app/js/search/controllers/SearchCtrl.js, app/js/search/controllers/TrackSearchCtrl.js, env.json
This PR limits all searches to GB region fixing a bug where in some cases it was searching all markets
=> Fix: Limit searches to GB region

app/js/playlist/controllers/PlaylistCtrl.js, tests/unit/playlist/controllers/PlaylistCtrl.js
Fixed an issue where the user was not being loaded with the track when a new track has been added to the playlist.
Fixes #142
=> Fix: User not loaded with song on add event

app/less/default/modules/track.less, app/partials/track.html
This PR remove the album from tracks on mobile due to space issues with track directive
=> Fix: Track height on mobile

app/index.html, app/js/player/controllers/PlayerCtrl.js, bower.json, scripts.json
This PR displays the current track in the title of the browser
Fixes #151
=> Feature: Song in title

app/js/stats/controllers/StatsCtrl.js, tests/unit/stats/controllers/StatsCtrl.js
This PR fixes #158, where to date was wrong in query.
=> Fix: historic stats loading

app/js/stats/stats.js
Inadvertently removed this in #171
=> Fix: timeFilter module dependency

app/js/player/directives/track.js, app/less/default/modules/track.less, app/less/mobile/modules/track.less, app/partials/stats.html, app/partials/track.html
=> Feature: add play count to top tracks

app/less/default/modules/controls.less, app/less/default/modules/footer.less, app/partials/footer.html, tests/e2e/specs/scenarios.js
=> Feature: hide controls for unauthorised user

app/js/search/controllers/ArtistDetailCtrl.js, app/less/default/core/variables.less, app/less/default/modules/artists.less, app/less/main.less, app/partials/artists-detail.html, app/partials/artists/album-list.html, app/partials/artists/related-artists.html, app/partials/artists/singles-list.html, app/partials/artists/top-tracks.html, tests/unit/search/controllers/ArtistDetailCtrl.js
See related artists in artist detail view. Also this PR makes use of tabs to separate sections in the artists detail page.
Fixes #166
=> Feature: Related artists

tests/e2e/specs/scenarios.js
=> Fix: Infinite scroll e2e test timing out

app/less/default/modules/images.less, app/partials/search/artist.html
=> Fix: Incorrect artist image in sidebar search

app/index.html, app/js/auth/services/SpotifyAuthService.js, app/js/search/directives/playlist.js, app/js/search/search.js, app/js/users/controllers/UserPlaylistDetailCtrl.js, app/js/users/controllers/UserPlaylistsCtrl.js, app/js/users/controllers/UserStatsCtrl.js, app/js/users/users.js, app/partials/search/playlist.html, app/partials/users/nav.html, app/partials/users/playlist-detail.html, app/partials/users/playlists.html, app/partials/users/profile.html, app/partials/users/stats.html, scripts.json, tests/unit/auth/controllers/LoginSpotifyCtrl.js, tests/unit/auth/services/SpotifyAuthService.js
This feature allows the user to view their Spotify playlists in the user profile
- `users/:userId/playlists` view
- `users/:userSpotifyId/playlists/:playlistId` view
- Playlist directive
- updates to `SpotifyAuth` Service
Fixes #193
=> Feature: User spotify playlists

README.md, app/partials/footer.html, circle.yml, tests/e2e/protractor.saucelabs.conf.js, tests/e2e/saucelabs.sh, tests/e2e/specs/scenarios.js
This PR runs e2e tests on saucelabs instead of inside circle
Fixes #185
=> Feature: Saucelabs

app/js/player/controllers/PlayerCtrl.js
This PR removes the unicode characters in the browser title and includes the artist name along with the track title.
=> Feature: Fix track in browser title

app/js/player/directives/track.js, app/less/default/modules/footer.less, app/less/default/modules/track.less, app/partials/albums-detail.html, app/partials/artists/top-tracks.html, app/partials/footer.html, app/partials/history.html, app/partials/player/current.html, app/partials/playlist.html, app/partials/search-result.html, app/partials/stats.html, app/partials/track-search.html, app/partials/track.html, app/partials/users/playlist-detail.html, app/partials/users/stats.html
Some albums contain tracks not available to play in the region set in the config, this PR hides the ability to add those tracks to the playlist.
Fixes #203
=> Fix: Hide tracks not available in region

CHANGELOG.md, app/js/player/controllers/PlayerCtrl.js, app/partials/player/controls.html, tests/unit/player/controllers/PlayerCtrl.js
* @edwardoparearyee: Fix: Volume slider (#210)
=> Release: 0.9.1

app/partials/users/stats.html
Integrated artist directive into user stats view.
=> Fix: artist display in user stats view

app/partials/footer.html
Fixed the toggle that displays the player controls for mobile not working. The issue was again scope.
Fixes #215
=> Fix: Mobile controls toggle

app/js/playlist/controllers/PlaylistCtrl.js, tests/unit/playlist/controllers/PlaylistCtrl.js
Updated event handler for delete to look for the uuid value in the playlist
Fixes #219
=> Fix: delete event handler

tests/e2e/protractor.conf.js, tests/e2e/specs/scenarios.js
This PR refactors the e2e tests to simplify and reduce the amount of time they take to complete. Hopefully this makes them more stable.
Fixes #223
=> Fix: Saucelabs tests failing regularly 

app/index.html, bower.json
=> Fix: Track in title element being removed on route change

CHANGELOG.md, app/js/playlist/controllers/PlaylistCtrl.js
* @edwardoparearyee: Fix: Track not added to playlist (#232)
=> Release: 0.9.3

app/js/playlist/controllers/PlaylistCtrl.js, tests/unit/playlist/controllers/PlaylistCtrl.js
Fixed a bug where tracks were not being added to an empty playlist
=> Fix: Track not being added to empty playlist

app/js/player/controllers/PlayerCtrl.js, app/js/player/services/TrackTimer.js, tests/e2e/specs/scenarios.js
Fixed a few bugs with the track timer where the value displayed would be incorrect after pausing the current track multiple times creating multiple instances of `$interval`.
Also removed calling event handlers after pressing a button as socket event will handle those.
Fixes #191
=> Fix: Incorrect track timer values

app/js/search/controllers/SearchCtrl.js, app/less/default/core/type.less, app/less/default/modules/albums.less, app/less/default/modules/media.less, app/less/main.less, app/partials/footer.html, app/partials/search-result.html, tests/unit/search/controllers/SearchCtrl.js
This fixes some invalid html in the player at the footer of the site and in the sidebar search.
I've removed the link to `/current` view for now and replaced the directives in the search sidebar with bootstrap `.media` items.
Fixes #240
=> Fix: invalid html

CHANGELOG.md, app/js/player/controllers/PlayerCtrl.js, app/js/player/services/TrackTimer.js, app/js/playlist/controllers/PlaylistCtrl.js, app/js/search/controllers/SearchCtrl.js, app/less/default/core/type.less, app/less/default/modules/albums.less, app/less/default/modules/media.less, app/less/main.less, app/partials/footer.html, app/partials/search-result.html, tests/e2e/specs/scenarios.js, tests/unit/playlist/controllers/PlaylistCtrl.js, tests/unit/search/controllers/SearchCtrl.js
* @edwardoparearyee: Fix: invalid html (#244)
* @edwardoparearyee: Fix: add delete track option without having to refresh playlist (#242)
* @edwardoparearyee: Fix: Incorrect track timer values (#241)
=> Release: 0.9.5
