thisissoon/FM-Frontend

- app/less/main.less
Fixes an issue where the `angular-material.css` was not being imported into `main.less` properly
> Fix: Angular material css import

- app/js/fm-api/factories/PlayerTransportResource.js
- app/js/fm-player/config.js
- app/js/fm-player/controllers/PlayerCtrl.js
- app/partials/player.html
- tests/unit/fm-api/factories/PlayerTransportResource.js
- tests/unit/fm-player/controllers/PlayerCtrl.js
This PR resolves current playback state from paused header on response from `/player/current` resource. Also adds explicit resume/pause functions on scope.
> Fix: transport

- app/js/fm-player/config.js
- app/js/fm-player/controllers/PlayerCtrl.js
- tests/unit/fm-player/controllers/PlayerCtrl.js
This PR corrects the resolve config by returning the `$promise` rather than resource instance.
> Fix: resolve promises

- Gruntfile.js
- app/index.html
- app/js/fm-player/app.js
- app/js/fm-player/config.js
- app/less/default/modules/menu.less
- app/less/main.less
- app/less/tablet/modules/menu.less
- app/partials/player.html
- env.json
This PR allows us to build a version of the FM frontend for phonegap by simply running `grunt build -env phonegap`.
I've added a `phonegap` environment in the environment config `env.json` and added the options needed to configure the app.
> Feature: Phonegap build

- app/js/fm-loading-screen/loadingScreen.js
- app/js/fm-socket/socket.js
The EVENTS constant used in fm-socket was conflicting with EVENTS constant declared in fm-loading-screen. I have now namespaced this as `FM_SOCKET_EVENTS`
> Fix: naming conflict, rename EVENTS => FM_SOCKET_EVENTS

- Gruntfile.js
- app/index.html
- app/js/fm-api/app.js
- app/js/fm-api/config.js
- app/js/fm-api/factories/RequestInterceptor.js
- env.json
- scripts.json
- tests/unit/fm-api/factories/RequestInterceptor.js
This adds auth configuration to `sn-fm-api` and a request interceptor to add the `Access-Token` header to FM API requests with the access token from local storage.
Once the interface for the login button has been finalised, the integration can be completed.
> Feature: auth integration

- app/index.html
- app/js/fm-api/factories/UsersResource.js
- app/js/fm-player/controllers/PlayerCtrl.js
- app/js/fm-player/directives/track.js
- app/less/default/core/reset.less
- app/less/default/modules/tracks.less
- app/less/mobile/modules/tracks.less
- app/partials/player.html
- app/partials/track.html
- scripts.json
- tests/unit/fm-player/controllers/PlayerCtrl.js
This implements https://github.com/thisissoon/FM-API/pull/13 https://github.com/thisissoon/FM-API/issues/12, adding user avatars to tracks in the queue. This is just positioned on the right of the track at block the moment. Perhaps a temporary position until the designs are finalised.
> Feature: users in queue

- app/index.html
- app/js/fm-api/factories/RequestInterceptor.js
- app/js/fm-player/app.js
- app/js/fm-player/constants/errors.js
- app/js/fm-player/controllers/LoginCtrl.js
- app/js/fm-player/controllers/PlayerCtrl.js
- scripts.json
- tests/unit/fm-api/factories/RequestInterceptor.js
- tests/unit/fm-player/app.js
- tests/unit/fm-player/controllers/LoginCtrl.js
- tests/unit/fm-player/controllers/PlayerCtrl.js
This is a proof of concept for handling in-view errors vs error on page-load.
Errors on page-load should trigger the relevant error page. In-view errors should be handled within their respective controller and trigger a dialog. 
At the moment I have only implemented this on the `toggleMute` action as a proof of concept for early review. Also the `authenticate` action will catch an error if user is not a member of SOON_ of This Here and display a dialog.
No tests yet. Needs more work before merge.
> Feature: inview error handling

- app/less/default/modules/spotify-search.less
This fixes #51 by re-positioning the `md-autocomplete` element to use the scrollbar of the dropdown rather than the sidebar.
> Fix: adjust autocomplete ul positioning

- app/js/player/controllers/PlayerCtrl.js
- tests/unit/player/controllers/PlayerCtrl.js
`<input type="range">` bizarrely works with strings so we need to parse this as an integer before posting to the API. Fixes #57
> Fix: volume slider

- Gruntfile.js
- app/less/default/core/glyphicons.less
So the issue was simple in the end, we weren't copying the font files during the build.
Fixes #59
> Fix: font icons

- app/index.html
- app/js/player/directives/slider.js
- app/js/player/player.js
- app/less/default/core/variables.less
- app/less/default/modules/controls.less
- app/partials/footer.html
- app/partials/slider.html
- scripts.json
- tests/unit/player/directives/slider.js
fmSlider directive to add fill to volume slider #73.
The directive makes use of ngModel so we can continue to use the built-in debounce features. For example:
```
<fm-slider
class="volume-control"
ng-model="volume"
ng-change="updateVol()"
ng-model-options="{
updateOn: 'default blur',
debounce: {
'default': 500,
'blur': 0
}
}"
data-min="0"
data-max="100">
</fm-slider>
```
> Feature: slider fill

- app/index.html
- app/js/api/api.js
- app/js/api/factories/PaginationInterceptor.js
- app/js/api/factories/PlayerHistoryResource.js
- app/js/history/controllers/HistoryCtrl.js
- scripts.json
- tests/unit/api/factories/PaginationInterceptor.js
- tests/unit/history/controllers/HistoryCtrl.js
Originally I wanted to attach the meta data as a property of the resource, something like `[ 0: {}, 1:{}, meta:{} ]` however this seems to get stripped by angular so an alternative solution could be to transform paginated resources to the following format `{ items: [], meta: { totalPages: 10, totalCount: 100 }}` as implemented below with an $httpInterceptor.
Let me know your thoughts or if you think there could be a better solution...
> Feature: fix pagination meta

- app/less/default/core/normalize.less
> Feature: Font smoothing

- app/js/player/controllers/PlayerCtrl.js
- tests/unit/player/controllers/PlayerCtrl.js
- tests/unit/player/services/TrackTimer.js
- use correct elapsed time property from API `player.elapsed_time`
- stop and reset timer on end event
- more unit tests
> Fix: track timer

- app/js/player/controllers/PlayerCtrl.js
- app/js/player/services/TrackTimer.js
- tests/unit/player/controllers/PlayerCtrl.js
- tests/unit/player/services/TrackTimer.js
The timer was setup to reset when calling `TrackTimer.start(..)` with a timer running. When the events are running and a user clicks resume `$scope.onResume` is called twice; once when the resume action is completed by the API and once on the resume socket event (thus this issue only affects the user who clicks the resume button as they are the only one to get the double call). As the issue is introduced only when the events are active it was not caught in our unit or e2e tests.
This PR:
- Stops the timer resetting on multiple calls to `.start()`, now the timer has to be explicitly reset with `.reset()`
- Renames the `stop` method to `pause` as that makes more sense
- Fixes #99
> Fix: track timer reset bug

- app/js/player/controllers/PlayerCtrl.js
- app/partials/footer.html
Fixed a bug where if a user logged into the player and there wasn't a track currently playing it would still display the controls and progress bar.
> Fix: Hide progress bar and controls if no current tracks

- app/less/default/modules/track.less
Stop the progress bar and timer changing length and being squashed when the track name/album/artist is long.
> Fix: Progress bar size

- app/partials/footer.html
So track was being defined from api even when there was no track as an empty object. So changed the check to look for a property inside the object
> Fix: Hide controls if no tracks

- app/index.html
- app/js/stats/filters/time.js
- app/js/stats/stats.js
- app/partials/stats.html
- scripts.json
- tests/unit/stats/filters/time.js
This PR adds a filter to split the total play time from milliseconds into mins, hours and days. The default angular date filter is optimised for date values and will try to work out the date from the milliseconds, instead it needs to be treated as an elapsed time. Fixes #157
> Fix: total play time stat

- app/index.html
- app/js/stats/controllers/StatsCtrl.js
- app/js/stats/services/DateUtils.js
- app/js/stats/services/StatsResolver.js
- app/js/stats/stats.js
- app/partials/stats.html
- scripts.json
- tests/unit/stats/controllers/StatsCtrl.js
- tests/unit/stats/services/DateUtils.js
- tests/unit/stats/services/StatsResolver.js
This PR improves the stat filtering:
- `DateUtils` helper service with method to determine the date of last Friday - this allows us to set filter limits and defaults based on actual week rather than just `today - 7 days`. (fixes #162)
- Set filter defaults in new `statsResolver` - this allows us to set defaults and restrict date filter params before the data is fetched (fixes #159)
- Currently users can access the current week stats if they manually set the filter params in the URL, the new `statsResolver` fixes that.
- Clearing the filters now shows the stats from all of time up to last Friday (fixes #161)
> Fix: stat filtering

- app/js/api/factories/RequestInterceptor.js
- app/js/auth/services/SpotifyAuthService.js
- tests/unit/auth/services/SpotifyAuthService.js
The PR fixes an issue with Spotify authentication flow when the token has expired. The FE will now request a new token when the token expires.
> Fix: Spotify Authentication

- app/js/stats/services/DateUtils.js
- app/js/stats/services/StatsResolver.js
- tests/unit/stats/services/DateUtils.js
- tests/unit/stats/services/StatsResolver.js
There is an issue with the method used to determine the dates of last week, it did not set the month correctly. This fixes it by using time based date calculation instead. I've also added restriction to the stats from date, so it can not be in the future. Fixes #200
> Fix: stat default from

- app/js/auth/services/SpotifyAuthService.js
- tests/unit/auth/services/SpotifyAuthService.js
This PR fixes an issue with Spotify authentication when the users token has expired. This should renew the token automatically for the user.
> Fix: spotify auth when has expired

- app/js/auth/controllers/LoginGoogleCtrl.js
- app/partials/users/nav.html
Hide the playlist link in the user profile view unless the user is logged in to Spotify and it is their own profile they are looking at.
> Fix: Hide playlist link when not logged in to spotify

- app/js/stats/controllers/StatsCtrl.js
- app/js/stats/services/StatsResolver.js
- app/js/users/controllers/UserStatsCtrl.js
- tests/unit/stats/services/StatsResolver.js
This PR makes the StatsResolver re-usable for different resources. When calling it the resource can be injected in `statsResolver(StatsResource.get, $route.current.params)`. This has been integrated into the `/users/:id/stats` to impose the same date filter restrictions as the `/stats` view. 
Fixes #218
> Fix: user stats filter

- app/js/api/factories/RequestInterceptor.js
- app/js/api/factories/UsersResource.js
- app/js/auth/services/SpotifyAuthService.js
- app/js/users/controllers/UserPlaylistsCtrl.js
- app/partials/header.html
- app/partials/users/nav.html
- app/partials/users/playlists.html
- tests/unit/auth/services/SpotifyAuthService.js
- tests/unit/users/controllers/UserPlaylistsCtrl.js
So this should be a temporary solution, the user will have to manually click to login to spotify when on their own profile playlists page.
This should stop the error message that appear when the user navigates to the player and their token has expired.
Fixes #211
> Fix: Spotify authtication error message

- app/js/playlist/controllers/PlaylistCtrl.js
Fixed an issue where if there are no items in the playlist and a track gets added it would not be added to the playlist until the page was refreshed.
The issue was that when there are no items in the queue the API didn't return total pages pagination data in the header which broke some logic in the FE.
Fixes #199
> Fix: Track not added to playlist

- env.json
This PR adds a config to build the FE to work with the new Frontend API.
To build simply run: `grunt build --env frontend-api`
- Eventually I'd imagine this will become the default for `development`
- Sockets still run in the API so for now the api would still need to be running in another service
> Feature: Frontend backend config

- app/js/socket/factories/PlayerQueueSocket.js
- app/js/socket/sails.js
- bower.json
- modules/index.html
- modules/socket/sails.html
This PR adds a prototype module for testing sails socket connectivity. This uses the [angualrSails](https://github.com/balderdashy/angularSails) module for sails angular bindings. This library alone would allow us to make requests like this:
```
sailsSocket.get("/player/queue").then...
```
and handle events like this:
```
sailsSocket.on("player/queue", function(message){
switch(message.verb){
case "created":
...
// check which event occured and respond accordingly
}
})
```
This library is structured similarly to $http however I felt we might prefer an approach similar to how we use $resource, so I have begun to investigate this through a `sailsResource` factory. This would allow us to have a resource like [PlayerQueueSocket](https://github.com/thisissoon/FM-Frontend/compare/feature/sails-s …
> Feature: sails socket

- app/js/playlist/controllers/PlaylistCtrl.js
- tests/unit/playlist/controllers/PlaylistCtrl.js
Fixed a bug where the "delete track" option would not appear until the playlist was refreshed. This is due to needing a `uuid` for the track which is only available from the `/queue` end point.
Fixes #220
> Fix: add delete track option without having to refresh playlist
